# Generated by Django 5.0.4 on 2024-04-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_name_userprofile_roll_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='seller',
            new_name='user',
        ),
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.CharField(default='Used', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='picture',
            field=models.ImageField(default='null', upload_to='item_pictures/'),
            preserve_default=False,
        ),
    ]
