# Generated by Django 5.0.4 on 2024-04-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_seller_item_user_item_condition_item_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='condition',
        ),
        migrations.AddField(
            model_name='item',
            name='bought_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], default='available', max_length=20),
        ),
    ]
