# Generated by Django 5.0.4 on 2024-04-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent_by_current_user',
            field=models.BooleanField(default=False),
        ),
    ]
