# Generated by Django 5.0.4 on 2024-04-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
